Basic Statistics
The science of collecting, organizing, presenting, analyzing, and interpreting data to assist in making more effective decisions.
Statistics: “a bunch of mathematics used to summarize, analyze, and interpret a group of numbers of observations
Independent and Dependent Variable
Variables are defiend as the properties or kinds of characteristics of certain events or objects.
Independent variables are variables that are manipulated or are changed and whose effects are measured and compared. The other name for independent variables is Predictor(s).
The independent variables are called as such because independent variables predict or forecast that values of the dependent variable.
Dependent variables refer to that type of variable that measures the affect of the independent variable(s). We can also say that the dependent variables are the types of variables that are completely dependent on the independent variable(s). The other name for the dependent variable is the Predicted variable(s).
Independent and Dependent Variables contd…
Independent variables are also called
Controlled variable
Explanatory variable
Input variable
Dependent variables are also called
Response variable,
Measured variable,
Observed variable,
Outcome variable,
Output variable,
Example 1
Steve loves gardening,. He decides to experiment to help him determine which fertilizer would be ideal for faster plant growth. He added different brands of fertilizer to different plans and observed their growth over time.
The dependent variable Steve will be working with is the increase in the height of each plant (from each separate brand). The independent variable would be the fertilizer brand.
Example2
Response variable: Yes or No to the Question “Do you smoke?”
Explanatory variable: Gender (Female or Male)
Example3
Response Variable: Weight
Explanatory variable: Diet
Types of variables/Data
Data:-
1 Catergorical 
Example
Martial Status
Political Party
Eye Color
(defined categories)
2Numerical 
2a Discrete
Examples:
Number of Children
Defects per hour (Counted Items)
2b Continuous
Examples
Weight
Voltage
(Measured characteristics)
1.Numerical Data
Numerical data can be subdivided into two types:
1.1Discrete Data
Discrete data refers to the measure of things in whole numbers (integers), For example, the number of purchased made by a customer in a year. Since the number of things that a person buys cannot be three and a half, or four and a third – it must be a whole number life four or five things – this kind of data falls under the discrete category.
1.2 Continuous data
In contrast to discrete data, continuous data includes all numbers possible between any tow integers or whole numbers. For example the height of something. It could be 9.2345 inches or 9.7219 inches, or any other fraction between the two whole numbers nine and ten.
2.Catergorical/Nominal Data (non numeric data)
This type of data is non-numeric
We use it to quantify things in categories like gender, ethnicity, nationality, political party, etc.
Gender ---Male,Female
Country ---US,UK,UAE
We can assign numbers to the categories, but the numbers would not, in that case, represent their value per say.
They will only separate one type from the other – type one from type two or three.
For example, while calclulating india’s population, Bangalore could be city number one, Mumbai number two and so on
3.Ordinal Data
Ordinal data is an amalgamation of numerical and categorical data. Simply put, this data type consists of categories that are in order.
The intervals between categories are not known.
Movie or music ratings that use stars to denote quality.
Numbers simply represent the good and bad categories.
A movie with a 5-star rating is obviously very good as opposed to a movie with only 1-star, which, very likely, is terrible.
Note that the numbers in this example do denote value.
Mathematically speaking, 5 is greater that 1. This difference in value is used to differentiate good films from bad. Good films receive a higher rating of 4 or 5, while bad films only get a lower rating of 1 or 2.
Interval Data
Data is this level can be orderedas it is in a range of values and meaningful differences between the data points can be calculated. Eg: Temperature in Celsius, Year of Birth
Types of statistics
Descriptive statistics are procedures used to summarize, organize, and make sense of a set of scores or observations.
Inferential statistics – procesures used that allow researchers to infer or generalize, observations made with samples to the larger population from wich they were selected.


In [10]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [11]:
a=np.array([34,56,37,12,19,90,88])
a

array([34, 56, 37, 12, 19, 90, 88])

In [12]:
np.mean(a)

48.0

In [13]:
np.median(a)

37.0

In [41]:
a.max()

90

In [42]:
a.min()

12

In [43]:
range_of_a=a.max()-a.min()
range_of_a

78

In [48]:
np.var(a)

840.2857142857143

In [53]:
round(np.var(a),2)

840.29

In [50]:
f=np.std(a)
f

28.987682113023702

In [51]:
(round(f,2))

28.99

In [14]:
b=np.array([100,200,300,400,500,600])
b

array([100, 200, 300, 400, 500, 600])

In [15]:
np.mean(b)

350.0

In [16]:
np.median(b)

350.0

In [19]:
p=np.array([[23,45],[66,44]])
p

array([[23, 45],
       [66, 44]])

In [20]:
np.mean(p,axis=0) #columnwise

array([44.5, 44.5])

In [21]:
np.mean(p,axis=1) #rowwise

array([34., 55.])

In [22]:
j=np.array([[12,15,16],[66,77,88],[34,33,99]])
j

array([[12, 15, 16],
       [66, 77, 88],
       [34, 33, 99]])

In [23]:
np.mean(j,axis=0) #(columnwise)

array([37.33333333, 41.66666667, 67.66666667])

In [24]:
np.mean(j,axis=1)

array([14.33333333, 77.        , 55.33333333])

In [25]:
np.median(j,axis=0)

array([34., 33., 88.])

In [27]:
np.median(j,axis=1)

array([15., 77., 34.])

In [31]:
import numpy as np
import pandas as pd
import scipy
from scipy import stats
from scipy.stats import percentileofscore

In [32]:
#github/dataset1
df=pd.read_csv('student_marks.csv')
df

Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45         56       87       21   
1    Suresh      M  04-05-1987     75       96         78       64       90   
2    Ramesh      M  25-05-1989     25       54         89       76       95   
3   Jessica      F  12-08-1990     78       96         86       63       54   
4  Jennifer      F  02-09-1989     58       96         78       46       96   
5      Annu      F  05-04-1988     45       87         52       89       55   
6     pooja      F  04-05-1987     55       64         61       58       75   
7    Ritesh      M  25-05-1989     54       76         87       56       25   
8     Farha      F  12-08-1990     55       63         89       75       78   
9    Mukesh      M  02-09-1989     96       46         77       83       58   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53  
5         89       87      52  
6         58       64      61  
7         56       76      87  
8         75       63      89  
9         83       46      77

In [33]:
df['Maths'].mean()

59.6

In [34]:
df['English'].mean()

69.7

In [35]:
df['Chemistry'].mean()

75.3

In [36]:
df['Maths'].median()

55.0

In [37]:
df['Civics'].median()

63.0

In [38]:
df['Maths'].mode()

0    55
Name: Maths, dtype: int64

In [39]:
df['Physics'].mode()

0    96
Name: Physics, dtype: int64

Descriptive statistics contid….
Descriptive statistics
1.Measures of center
1a.Mean
2b.Median
2c.Mode
2.Measures of dispersion
2a.Range
2b.Percentiles/Quartiles
2c.IQR
2d.Variance
2e.Standard Deviation
2f.Skewness
2g.Kurtosis

Mean
The average of the given values. To compute mean, sum all the values and divide the sum by the number of values.
MEAN = X = x/n

Median
The Median is the middle value for a dataset that has been arranged in order of magnitude.
If the total number of values is odd then 
Median = (n+1)th/2 term
If the total number of values is even then
Median = ((n/2)th term + (n/2+1)th term)th term
Median = (1+2)/2=1.5
Median is 1.5

Mode
The value in a data set that occurs most often or most frequenctly.
Example: 2,3,3,3,4,4,4,4,7,7,8,8,8
Mode=4

Descriptive statistics
2.Measures of dispersion
2a.Range
	Largest value and smallest value.

2d.Variance


2e.Standard Deviation

Variance

Variance measures how far is the sum of squared distances from each point to the mean i.e the dispersion around the mean.
Variance is the average of all squared deviations.

x-)2(square)/n for populations (=mean)

Standard deviation is …
The square root of variance.

S = XXsquare

Where s = the standard deviation of a sample
Means “sum of” 
X = each value in the data set
X = mean of all values in the data set
N= number of values in the data set

For eg:{3,5,6,9,10} are the values in dataset.

Mean = (3+5+6+9+10)/5=6.6
Variance=[(3-6.6)2 + (5-6.6)2 + (6-6.6)2+(9-6.6)2+(10-6.6)2]/5
=(12.96+2.56+0.36+5.76+11.56)/5=33.2/5=6.64
Standard Deviation=Variance=6.64=2.576


In [40]:
np.var(b)

29166.666666666668

In [54]:
round(np.var(b),2)

29166.67

In [55]:
np.std(b)

170.78251276599332

In [56]:
round(np.std(b),2)

170.78

In [58]:
rang=b.max()-b.min()
rang

500