# Numpy

Data Science Libraries
Numpy
Numerical Python
Numpy Tutorial
NumPy is a Python package. It stands for ‘Numerical Python’. It is library consisting of multidimensional array objects and a collection or routines for processing of array.


In [1]:
import numpy
numpy.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [2]:
numpy.array([11,12,13,14,15])

array([11, 12, 13, 14, 15])

In [3]:
a=numpy.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [4]:
b=numpy.array([90,30,56,34,29,77,12])
b

array([90, 30, 56, 34, 29, 77, 12])

In [5]:
import numpy as np
a=np.array([90,92,93,88,55,76,12,35])
a

array([90, 92, 93, 88, 55, 76, 12, 35])

In [6]:
a=np.array([1,2,3,4,5]), ([1,2,3,4,5])
a

(array([1, 2, 3, 4, 5]), [1, 2, 3, 4, 5])

In [7]:
#count the number of elements
a.size

AttributeError: 'tuple' object has no attribute 'size'

In [8]:
#dimention
a.ndim

AttributeError: 'tuple' object has no attribute 'ndim'

In [9]:
#size
b.size

7

In [10]:
a.shape

AttributeError: 'tuple' object has no attribute 'shape'

In [11]:
b.shape

(7,)

In [12]:
c=np.array([[1,2], [3,4]])
c

array([[1, 2],
       [3, 4]])

In [13]:
c.shape

(2, 2)

In [14]:
d=np.array([[29,39], [87,45]])
d

array([[29, 39],
       [87, 45]])

In [15]:
d.shape

(2, 2)

In [16]:
e=np.array([[10,20], [30,40], [50,60]])
e

array([[10, 20],
       [30, 40],
       [50, 60]])

In [17]:
e.shape

(3, 2)

In [18]:
f=np.array([[1,2,3], [4,5,6]])
f


array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
f.shape

(2, 3)

In [20]:
f.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
f.min()

1

In [22]:
f.max()

6

In [23]:
f.size

6

In [24]:
f.dtype

dtype('int32')

In [25]:
#int 32/8 = 4bytes (itemsize)
f.itemsize

4

In [26]:
j=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
j.shape

(4, 4)

In [28]:
j.size

16

In [29]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [30]:
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [31]:
a=x.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
a=x.reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
x=np.arange(25)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [34]:
a=x.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
a=np.arange(35).reshape(5,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [36]:
a.shape

(5, 7)

In [37]:
a.dtype

dtype('int32')

In [38]:
#gives the number of bytes/memory occupied by each element
a.itemsize

4

In [39]:
a.size

35

In [40]:
type(a)

numpy.ndarray

In [41]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [42]:
type(b)

numpy.ndarray

In [43]:
import numpy as np
b=np.array([[1.5,2,3],[4,5,6]],dtype='float32')
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [44]:
ra=np.array([[34,78,89],[22,33,77]])
ra

array([[34, 78, 89],
       [22, 33, 77]])

In [45]:
print(ra.ravel())

[34 78 89 22 33 77]


In [46]:
import numpy as np
b=np.array([[1.5,2,3],[4,5,6]],dtype='int32')
b

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [52]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [53]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
#Broadcasting in Numpy
#The term broadcasing describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is ‘broadcast’ across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing operations.

In [55]:
a=np.array([1.0,2.0,3.0])
b=np.array([1.0,2.0,2.0])
a*b

array([1., 4., 6.])

In [56]:
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [57]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [58]:
c=a-b
print(c)

[20 29 38 47]


In [59]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [60]:
b=np.random.random([2,3])
b

array([[0.9433651 , 0.96657949, 0.27269766],
       [0.759891  , 0.05329792, 0.41464477]])

In [61]:
c=np.ones([2,3])
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
d=b+c
d

array([[1.9433651 , 1.96657949, 1.27269766],
       [1.759891  , 1.05329792, 1.41464477]])

In [63]:
#Universal Functions:
B=np.arange(3)
B

array([0, 1, 2])

In [64]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [65]:
c=np.array([2,1,4])
np.add(B,c)

array([2, 2, 6])

In [66]:
#Indexing Slicing and literating
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a[2]

2

In [68]:
a[2:5]

array([2, 3, 4])

In [69]:
a[-1]

9

In [70]:
a[-2]

8

In [71]:
a[-3]

7

In [72]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a[-4:]

array([6, 7, 8, 9])

In [74]:
a[-4:-2]

array([6, 7])

In [75]:
d2=np.arange(20)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
d2[5:] #slicing from 5th index till end of the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [77]:
d3=np.array([np.nan,1,2,3,np.nan,6,7,8])
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

In [78]:
np.random.rand(2,2)

array([[0.46124805, 0.61520496],
       [0.22655297, 0.86843219]])

In [79]:
#Randn (+ & - value) will generate any number for normal distribution in the given dimension format

In [80]:
np.random.randn(2,3)

array([[ 0.94546932, -0.28400513,  1.39758699],
       [ 1.29362337, -1.27498158, -0.44740767]])

In [81]:
#Done With Numpy