Data Science Libraries
Numpy
Numerical Python
Numpy Tutorial
NumPy is a Python package. It stands for ‘Numerical Python’. It is library consisting of multidimensional array objects and a collection or routines for processing of array.


In [1]:
import numpy
numpy.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [3]:
numpy.array([11,12,13,14,15])

array([11, 12, 13, 14, 15])

In [4]:
a=numpy.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [5]:
b=numpy.array([90,30,56,34,29,77,12])
b

array([90, 30, 56, 34, 29, 77, 12])

In [6]:
import numpy as np
a=np.array([90,92,93,88,55,76,12,35])
a

array([90, 92, 93, 88, 55, 76, 12, 35])

In [23]:
a=np.array([1,2,3,4,5]), ([1,2,3,4,5])
a

(array([1, 2, 3, 4, 5]), [1, 2, 3, 4, 5])

In [10]:
#count the number of elements
a.size

8

In [68]:
a.ndim

2

In [11]:
b.size

7

In [12]:
a.shape

(8,)

In [13]:
b.shape

(7,)

In [14]:
c=np.array([[1,2], [3,4]])
c

array([[1, 2],
       [3, 4]])

In [15]:
c.shape

(2, 2)

In [16]:
d=np.array([[29,39], [87,45]])
d

array([[29, 39],
       [87, 45]])

In [17]:
d.shape

(2, 2)

In [18]:
e=np.array([[10,20], [30,40], [50,60]])
e

array([[10, 20],
       [30, 40],
       [50, 60]])

In [19]:
e.shape

(3, 2)

In [20]:
f=np.array([[1,2,3], [4,5,6]])
f


array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
f.shape

(2, 3)

In [34]:
f.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
f.min()

1

In [26]:
f.max()

6

In [27]:
f.size

6

In [28]:
f.dtype

dtype('int32')

In [29]:
f.itemsize

4

In [30]:
j=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
j.shape

(4, 4)

In [32]:
j.size

16

In [35]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [36]:
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [37]:
a=x.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
a=x.reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
x=np.arange(25)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [40]:
a=x.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
a=np.arange(35).reshape(5,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [42]:
a.shape

(5, 7)

In [43]:
a.dtype

dtype('int32')

In [44]:
a.itemsize

4

In [45]:
a.size

35

In [47]:
type(a)

numpy.ndarray

In [48]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [49]:
type(b)

numpy.ndarray

In [51]:
import numpy as np
b=np.array([[1.5,2,3],[4,5,6]],dtype='float32')
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [52]:
ra=np.array([[34,78,89],[22,33,77]])
ra

array([[34, 78, 89],
       [22, 33, 77]])

In [53]:
print(ra.ravel())

[34 78 89 22 33 77]


In [55]:
import numpy as np
b=np.array([[1.5,2,3],[4,5,6]],dtype='int32')
b

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [59]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [61]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [64]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
#Broadcasting in Numpy
#The term broadcasing describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is ‘broadcast’ across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing operations.

In [70]:
a=np.array([1.0,2.0,3.0])
b=np.array([1.0,2.0,2.0])
a*b

array([1., 4., 6.])

In [71]:
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [72]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [74]:
c=a-b
print(c)

[20 29 38 47]


In [75]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [76]:
b=np.random.random([2,3])
b

array([[0.84283886, 0.61841989, 0.70408432],
       [0.83630421, 0.22652565, 0.56889029]])

In [77]:
c=np.ones([2,3])
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
d=b+c
d

array([[1.84283886, 1.61841989, 1.70408432],
       [1.83630421, 1.22652565, 1.56889029]])

In [80]:
#Universal Functions:
B=np.arange(3)
B

array([0, 1, 2])

In [82]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [84]:
c=np.array([2,1,4])
np.add(B,c)

array([2, 2, 6])

In [85]:
#Indexing Slicing and literating
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a[2]

2

In [87]:
a[2:5]

array([2, 3, 4])

In [88]:
a[-1]

9

In [89]:
a[-2]

8

In [90]:
a[-3]

7

In [91]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a[-4:]

array([6, 7, 8, 9])

In [93]:
a[-4:-2]

array([6, 7])

In [96]:
d2=np.arange(20)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [97]:
d2[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [98]:
d3=np.array([np.nan,1,2,3,np.nan,6,7,8])
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

In [100]:
np.random.rand(2,2)

array([[0.40435429, 0.09193503],
       [0.70031316, 0.64519215]])

In [ ]:
#Randn (+ & - value) will generate any number for normal distribution in the given dimension format

In [102]:
np.random.randn(2,3)

array([[-0.00561776, -1.08889738,  1.35078816],
       [ 0.91895977,  0.92655046,  1.7157078 ]])